### ISSUE TITLE
video unavailable 

### ISSUE THREAD

**Issue by agilealpha1** [jazzband/django-embed-video#127] opened 2020-05-30 07:10 UTC
![スクリーンショット 2020-05-30 15 48 02](https://user-images.githubusercontent.com/49577021/83322101-f6088d00-a28f-11ea-9bad-906f23285796.png)

**Comment by sudhanshu456** [comment] 2020-06-10 08:54
please state your problem correctly and provide the related code, which you used to implement this .!!

**Comment by pavlov-victor** [comment] 2020-07-02 14:43
I have same problem with this code
```
{% load embed_video_tags %}

{% video item.url 'small' %}
```
or
```
{% video item as my_video %}
    URL: {{ my_video.url }}
    Thumbnail: {{ my_video.thumbnail }}
    Backend: {{ my_video.backend }}
    {% video my_video 'small' %}
{% endvideo %}
```

browser - Yandex browser latest
country - Rus

**Comment by 221BBakerSt** [comment] 2020-08-03 21:59
I've got the same trouble as well @Jazzband

**Comment by aleksihakli** [comment] 2020-12-18 17:28
Is this issue still relevant? We haven't heard back in a while and I'm just checking if you are still facing the problem.

**Comment by 221BBakerSt** [comment] 2020-12-18 17:36
> Is this issue still relevant? We haven't heard back in a while and I'm just checking if you are still facing the problem.

I figured it out. The problem is some videos are set by the Youtuber not to be allowed to share. So it works for most videos.

**Comment by aleksihakli** [comment] 2020-12-18 17:39
Great, closing the issue then :) Thanks for reporting back.

**Closed by aleksihakli** 2020-12-18 17:39 UTC

**Comment by Segelzwerg** [comment] 2024-08-15 21:50
Sorry, for reviving an old issue. However, I faced a similar issue today.
For me it was resolved by adding this setting: `SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"`
And using HTTPS.
