### ISSUE TITLE
Video not showing on frontend

### ISSUE THREAD

**Issue by reyesvicente** [jazzband/django-embed-video#105] opened 2019-08-20 11:11 UTC
Hi, 

I'm new in using this package. I followed the docs and everything is smooth sailing. But the videos won't show on the front end. On the admin, I placed the URL of a YouTube video for the models ```video = EmbedVideoField(verbose_name='Videos', help_text='Videos of Translation')``` and 
<pre>
{% video object.video as amlvideo %}
Backend: {{ amlvideo.backend }}
URL: {{ amlvideo.url }}
Code: {{ amlvideo.code }}
Thumbnail: {{ amlvideo.thumbnail }}
HTTPS: {% if amlvideo.protocol == 'https' %}Yes{% else %}No{% endif %}

{% video amlvideo "large" %}
{% endvideo %}</pre>on my template but it's not showing.

Here are my ```models.py```

<pre>
from embed_video.fields import EmbedVideoField

class AMLVideo(models.Model):

    LANGUAGE = (
        ('LAN', 'Language'),
        ('FR', 'French'),
        ('EN', 'English'),
        ('HIN', 'Hindi'),
        ('SPA', 'Spanish'),
        ('GER', 'German'),
    )

    LEVEL = (
        ('BEG', 'Beginner'),
        ('INT', 'Intermediary'),
        ('ADV', 'Advanced'),
    )

    CATEGORY = (
        ('ANI', 'Animal'),
        ('ENV', 'Environmental'),
        ('MOR', 'Moral'),
        ('FOLK', 'Folktales'),
        ('ADN', 'Adventure'),
        ('POE', 'Poems'),
        ('FUN', 'Funny'),
    )

    title = models.CharField(max_length=100, default=None)
    level = models.CharField(max_length=100, choices=LEVEL)
    language = models.CharField(max_length=100, choices=LANGUAGE)
    category = models.CharField(max_length=100, choices=CATEGORY)
    video = EmbedVideoField(verbose_name='Videos',
                            help_text='Videos of Translation')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "video"
        verbose_name_plural = "videos"
</pre>

What could I do with this?

**Comment by aleksihakli** [comment] 2019-08-26 09:52
Hey! Do you have the `embed_video` application in your `INSTALLED_APPS` [as per the documentation](https://django-embed-video.readthedocs.io/en/v1.2.0/installation.html)?

What is your video URL? The package only supports YouTube, Vimeo, and SoundCloud videos at the moment. You can check out the support in the [backends](https://github.com/jazzband/django-embed-video/blob/master/embed_video/backends.py) module.

Do you get a stacktrace or error of any kind from your templates or applications when you add the video or try to access it in your views?

**Comment by reyesvicente** [comment] 2019-08-26 11:40
> Hey! Do you have the `embed_video` application in your `INSTALLED_APPS` [as per the documentation](https://django-embed-video.readthedocs.io/en/v1.2.0/installation.html)?
> 
> What is your video URL? The package only supports YouTube, Vimeo, and SoundCloud videos at the moment. You can check out the support in the [backends](https://github.com/jazzband/django-embed-video/blob/master/embed_video/backends.py) module.
> 
> Do you get a stacktrace or error of any kind from your templates or applications when you add the video or try to access it in your views?

Yes, I have the ```embed_video``` on my ```INSTALLED_APPS```.

I added the youtube URL on the Django Admin as a super user. Once I hit submit, the video got embedded INSIDE the admin, not on the template.

I saw a thumbnail error from one of the tags if I remember it correctly.

**Comment by aleksihakli** [comment] 2019-08-26 13:08
Well, it seems the admin works, so the problem is most likely with your template and HTML rendering. I'd check and fix any errors there first. YouTube videos should work correctly if they are public.

**Comment by reyesvicente** [comment] 2019-08-26 15:54
> Well, it seems the admin works, so the problem is most likely with your template and HTML rendering. I'd check and fix any errors there first. YouTube videos should work correctly if they are public.

What's the easiest way to show it on the template? I need a row of 3 youtube videos. 

How would you fix this?
```{% video object.video as amlvideo %}
Backend: {{ amlvideo.backend }}
URL: {{ amlvideo.url }}
Code: {{ amlvideo.code }}
Thumbnail: {{ amlvideo.thumbnail }}
HTTPS: {% if amlvideo.protocol == 'https' %}Yes{% else %}No{% endif %}

{% video amlvideo "large" %}
{% endvideo %}```

**Comment by reyesvicente** [comment] 2019-08-26 16:24
I got this error
```Backend wasn't recognised (``)
Traceback (most recent call last):
  File "/Users/highcenoid/Dev/Django/planetread/env/lib/python3.7/site-packages/embed_video/templatetags/embed_video_tags.py", line 112, in render
    backend = self.get_backend(url, context=context, **options)
  File "/Users/highcenoid/Dev/Django/planetread/env/lib/python3.7/site-packages/embed_video/templatetags/embed_video_tags.py", line 164, in get_backend
    else detect_backend(str(backend_or_url))
  File "/Users/highcenoid/Dev/Django/planetread/env/lib/python3.7/site-packages/embed_video/backends.py", line 62, in detect_backend
    raise UnknownBackendException
embed_video.backends.UnknownBackendException```

**Comment by aleksihakli** [comment] 2019-08-26 18:09
If you take a look at the [source code where the error happens](https://github.com/jazzband/django-embed-video/blob/dc3f8b1fca10ffc892469925f6ce034b09337067/embed_video/templatetags/embed_video_tags.py#L116) you can see that the backend URL should be included in the error message, but it seems like your URL isn't resolved in the `video` template tag correctly.

You are most probably using the template wrong and need to fix it. Try and remove lines one by one and see which line(s) break the functionality, then fix those parts.

The amount of source code in this package is fairly small so reading through the relevant error lines in the repository should prove helpful.

**Closed** 2019-08-30 07:56 UTC
Labels: question

**Comment by Roshik33** [comment] 2020-04-26 10:28
reyesvicente .. bind the video inside the for 
{% load embed_video_tags %}

{% for items in allitems %}
<div><p>{{items.title}}</p>

{% video items.video as my_video %}

  {% video my_video "large" %}
{% endvideo %}


{% video my_video '800x600' %}
	</div>
	{% endfor %}

views.py
def home(request):
   allItems= Item.objects.all()
   context= {'allitems': allItems}
   return render(request, 'post/post_detail.html',context)

> I got this error
> `` Backend wasn't recognised (``) Traceback (most recent call last): File "/Users/user/Dev/Django/planetread/env/lib/python3.7/site-packages/embed_video/templatetags/embed_video_tags.py", line 112, in render backend = self.get_backend(url, context=context, **options) File "/Users/user/Dev/Django/planetread/env/lib/python3.7/site-packages/embed_video/templatetags/embed_video_tags.py", line 164, in get_backend else detect_backend(str(backend_or_url)) File "/Users/user/Dev/Django/planetread/env/lib/python3.7/site-packages/embed_video/backends.py", line 62, in detect_backend raise UnknownBackendException embed_video.backends.UnknownBackendException ``

reyesvicente .. bind the video inside the for 
{% load embed_video_tags %}

{% for items in allitems %}
<div><p>{{items.title}}</p>

{% video items.video as my_video %}

  {% video my_video "large" %}
{% endvideo %}


{% video my_video '800x600' %}
	</div>
	{% endfor %}

views.py
def home(request):
   allItems= Item.objects.all()
   context= {'allitems': allItems}
   return render(request, 'post/post_detail.html',context)

models.py
from embed_video.fields import EmbedVideoField
class Item(models.Model):
    title = models.CharField(max_length=50)
    video = EmbedVideoField(verbose_name="My video", help_text="This is a help text")

    def __unicode__(self):
        return self.title

**Comment by reyesvicente** [comment] 2020-04-26 18:45
Posting a solution for the benefit of everyone:

```
...
{% load embed_video_tags %}
{% video item.video 'small' %}
...

{% if videos %}
{% for v in videos %}
{% video v.video as my %}
<iframe width="{{ 380 }}" height="{{ 225 }}" src="{{ my.url }}" frameborder="0" allowfullscreen></iframe>
{% endvideo %}
{% endfor %}
```
